\ProvidesClass{fime}
\LoadClass[10pt]{article}
\usepackage{wallpaper}
\usepackage[margin=0.95in,footskip=0.25in, bottom=0.5in]{geometry}
\CenterWallPaper{1}{fondo.pdf}
\pagenumbering{gobble}

\def\titulo{Inventarios forestales a través del procesamiento de imágenes}
\def\autor{José Angel Ramírez Cantú}
\def\matricula{1628685}
\def\grado{Ingeniero en Tecnología de Software}

\def\fecha{05 de Noviembre de 2020}
\def\asesor{Dra.\ Satu Elisa Schaeffer}
\def\revisorA{Dra.\ Sara Elena Garza Villarreal}
\def\revisorB{Dra.\ Sara Verónica Rodríguez Sánchez}
\def\director{Dr.\ Fernando Banda Muñoz}